language: cpp

before_script:
    - pwd
    - ls -l
    - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
    - sudo apt-get update -qq
    - sudo apt-get install cmake gcc-arm-none-eabi --yes -qq
    - which arm-none-eabi-gcc

script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/gcc-STM32.cmake -DCMAKE_BUILD_TYPE=DEBUG && make -j 8



