language: cpp

before_install:
    - sudo apt-get update
    - sudo apt-get install cmake --yes -qq

install:
    - tar -xf gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2
    - export TC_DIR=$PWD/gcc-arm-none-eabi-4_9-2015q3

before_script:
    - echo $TC_DIR
    - $TC_DIR/bin/arm-none-eabi-gcc --version

script:
    - $TC_DIR/bin/arm-none-eabi-g++ --version
    - mkdir build && cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/gcc-STM32.cmake -DCMAKE_BUILD_TYPE=DEBUG -DTOOLCHAIN_PREFIX=${TC_DIR} && make -j 8



