language: cpp

before_script:
    - pwd
    - ls -l
    - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update -qq
    - sudo apt-get install cmake gcc-arm-none-eabi --yes

script:
    - pwd
    - ls -l
    - mkdir build
    - pwd
    - ls -l
    - cd build
    - pwd
    - ls -l
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/gcc-STM32.cmake -DTOOLCHAIN_PREFIX="" -DCMAKE_BUILD_TYPE=DEBUG
    - make -j 8



